[browser]
gatherUsageStats = false

[server]
headless = true
maxUploadSize = 15

[theme]
primaryColor = "#1677C8"
backgroundColor = "#F5F9FD"
secondaryBackgroundColor = "#E7F1FA"
textColor = "#102A43"
font = "sans serif"
